full_name: Vector
description: Vector is a lightweight tool for building observability pipelines. As soon as solutions are enabled in the configuration, Vector starts to send their logs to the configured Loki instance. The latter can be either on-premise or in the cloud, the only condition being to permit authentication via username and API token.
references:
  - https://vector.dev/
  - https://github.com/vectordotdev/vector
maturity: PRODUCTION
categories:
  - LOG_SHIPPER
