full_name: ClamAV
description: ClamAV is an open source (GPLv2) anti-virus toolkit, designed especially for e-mail scanning on mail gateways. It provides a number of utilities including a flexible and scalable multi-threaded daemon, a command line scanner and advanced tool for automatic database updates. The core of the package is an anti-virus engine available in a form of shared library.
references:
  - https://www.clamav.net/
  - https://github.com/Cisco-Talos/clamav
  - https://docs.clamav.net/Introduction.html
maturity: PRODUCTION
categories:
  - ANTIMALWARE
  - HOST_PROTECTION