name: Bug Report
description: Report a bug in MutableSecurity
labels: ["bug-report"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What did you expect to happen when using MutableSecurity? What happened?
      placeholder: Description
    validations:
      required: true
  - type: input
    id: software-version
    attributes:
      label: Software Version
      description: Which version of MutableSecurity have you used?
      placeholder: v0.1.0
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: Operating System
      description: Which operating systems you use for running MutableSecurity? You may select more than one.
      options:
        - Linux
        - Windows
      multiple: true
    validations:
      required: true
  - type: input
    id: contact-details
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need additional information?
      placeholder: contact@john.me
    validations:
      required: false