name: Feature Request
description: Request a feature in MutableSecurity
labels: ["feature-request"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature do you want to see in MutableSecurity?
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: Do you see a possible solution for this feature?
      placeholder: Solution
    validations:
      required: false
  - type: input
    id: contact-details
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need additional information?
      placeholder: contact@john.me
    validations:
      required: false