name: Improvement
description: Improve the existent codebase of MutableSecurity
labels: ["improvement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Improvement Description
      description: What improvement do you want to make in MutableSecurity's codebase?
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: Do you see a possible solution for this improvement?
      placeholder: Solution
    validations:
      required: false
  - type: input
    id: contact-details
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need additional information?
      placeholder: contact@john.me
    validations:
      required: false