name: Ask a question
description: Please open an issue
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What is your question about MutableSecurity?
      placeholder: Question
    validations:
      required: true
  - type: input
    id: software-version
    attributes:
      label: Software Version
      description: Which version of MutableSecurity you use?
      placeholder: v0.1.0
    validations:
      required: false
  - type: dropdown
    id: operating-systems
    attributes:
      label: Operating System
      description: Which operating systems you use for running MutableSecurity? You may select more than one.
      options:
        - Linux
        - Windows
      multiple: true
    validations:
      required: false
  - type: input
    id: contact-details
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need additional information?
      placeholder: contact@john.me
    validations:
      required: false