full_name: Suricata
description: Suricata is the leading independent open source threat detection engine. By combining intrusion detection (IDS), intrusion prevention (IPS), network security monitoring (NSM) and PCAP processing, Suricata can quickly identify, stop, and assess even the most sophisticated attacks.
references:
  - https://suricata.io
  - https://github.com/OISF/suricata
maturity: REFACTORING
categories:
  - NETWORK_IDPS
