full_name: Wazuh Manager
description: Wazuh is an unified XDR and SIEM protection for endpoint and cloud workloads. The Manager is the central server in the Wazuh architecture. It analyzes the data received from all registered agents and triggers alerts when an event coincides with a rule.
references:
  - https://wazuh.com
  - https://github.com/wazuh/wazuh
maturity: REFACTORING
categories:
  - XDR
  - SIEM
