full_name: teler Real-time HTTP Intrusion Detection
description: teler is an real-time intrusion detection and threat alert based on web log.
references:
  - https://github.com/kitabisa/teler
maturity: UNDER_DEVELOPMENT
