full_name: teler
description: teler is a real-time intrusion detection and threat alert based on web log. Targets only nginx installed on Ubuntu.
references:
  - https://teler.app
  - https://github.com/kitabisa/teler
maturity: PRODUCTION
categories:
  - WEB_IDS
