from abc import ABC, abstractmethod

from pyinfra.api import Host, State


class AbstractSolution(ABC):
    """Abstract class wrapping a security solution"""

    _configuration: dict
    meta: dict
    result: dict

    @staticmethod
    @abstractmethod
    def get_configuration(state: State, host: Host):
        """Retrieves the configuration of the running solution.

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def _set_default_configuration(state: State, host: Host, aspect: str, value: str):
        """Overwrites the local configuration with the default one.

        It can be called by methods which resets the configuration to its
        default state (for example, install).

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host
            aspect (str): Set aspect
            value (str): Set value

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def _verify_new_configuration(state: State, host: Host, aspect, value):
        """Verifies a configuration that needs to be set.

        This method is automatically called by set_configuration.

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host
            aspect (str): Set aspect
            value (str): Set value

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def set_configuration(state: State, host: Host, aspect=None, value=None):
        """Sets an aspect of the configuration.

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host
            aspect (str): Set aspect
            value (str): Set value

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def _set_configuration_callback(state: State, host: Host, aspect, value):
        """Executes operations after the configuration setting.

        If overwritten, it is called automatically by set_configuration to
        perform post-setting operations.

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host
            aspect (str): Set aspect
            value (str): Set value

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def _put_configuration(state: State, host: Host):
        """Uploads the local configuration to the target host.

        This method is automatically called by set_configuration and,
        optionnaly, by methods that modifies the configuration (for example,
        install).

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def install(state: State, host: Host):
        """Installs the solution in the target host.

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def test(state: State, host: Host):
        """Tests the proper functioning of the running solution.

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def get_logs(state: State, host: Host):
        """Retrieves the logs generated by the solution.

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def get_stats(state: State, host: Host):
        """Retrieves the stats generated by the solution.

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def update(state: State, host: Host):
        """Updates the solution to its latest version.

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def uninstall(state: State, host: Host):
        """Uninstalls the solution from the target host.

        Args:
            state (State): pyinfra's state
            host (Host): pyinfra's host

        Raises:
            NotImplementedError: Method not implemented
        """
        raise NotImplementedError
