name: Updates the solutions' API call graph
on:
  push:
    branches:
      - main
    paths:
      - "mutablesecurity/solutions/base/solution.py"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository content
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - name: Execute the Python script
        run: |
          source .venv/bin/activate
          python3 others/api_call_graph_script/generate.py
      - name: Commit the changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -a -m "Updates the solutions' API call graph"
      - name: Push the commit
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
