name: Updates the solutions' API call graph
on:
  push:
    branches:
      - main
    paths:
      - "mutablesecurity/solutions/base/solution.py"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository content
        uses: actions/checkout@v2
      - name: Installs Graphviz
        run: sudo apt install -y graphviz
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Execute the Python script
        run: poetry run python3 others/api_call_graph_script/generate.py
      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Updates the solutions' API call graph
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: workflow-api-call-graph
          delete-branch: true
          title: Updates the solutions' API call graph
          labels: |
            autogenerated-content
