name: Executes unit testing and coverage reporting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository content
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Create a configuration file
        run: |
          echo 'developer_mode: True' > .mutablesecurity
      - name: Run pytest
        run: |
          poetry run coverage run -m pytest tests/ --ignore=tests/solutions/test_invalid_commands.py
          poetry run coverage run -a -m pytest tests/solutions/test_invalid_commands.py
      - name: Report coverage to Coveralls
        run: poetry run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
