name: Updates README.md
on:
  push:
    branches:
      - main
    paths:
      - "others/readme_generation_script/README.template.md"
      - "mutablesecurity/solutions/implementations/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository content
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run the generation script
        run: poetry run python3 others/readme_generation_script/generate.py
      - name: Commit the changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -a -m "Automatically updates README.md"
      - name: Push the commit
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
