name: Updates README.md
on:
  push:
    branches:
      - main
    paths:
      - "others/readme_generation_script/README.template.md"
      - "mutablesecurity/solutions/implementations/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository content
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run the generation script
        run: poetry run python3 others/readme_generation_script/generate.py
      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Generates README.md
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: workflow-readme-update
          delete-branch: true
          title: Generates README.md
          labels: |
            autogenerated-content
