name: Trigger website to update
on:
  push:
    branches:
      - main
    paths:
      - others/spec_sheets_generation_script/exports/**
      - .github/workflows/website_trigger.yaml
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CROSS_REPO_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: "MutableSecurity",
              repo: "website",
              workflow_id: "update_autodocs.yml",
              ref: "main"
            })
