name: Trigger website to update
on:
  push:
    branches:
      - "main"
    paths:
      - "others/spec_sheets_generation_script/exports/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: "MutableSecurity",
              repo: "website",
              workflow_id: "update_autodocs.yml",
              ref: "main"
            })